### ISSUE TITLE
Enable entities to be referenced with provider

### ISSUE THREAD

**Issue by twsouthwick** [microsoft/developer-platform#53]
```[tasklist]
### Tasks
- [x] Remove the durable tasks infra for POST and replace with API (#45) (the GET will still cycle through all the providers to find what we need) #50
- [x] Add provider to entity ref #43 (https://github.com/microsoft/developer-platform/pull/50#discussion_r1462180691)
- [x] https://github.com/microsoft/developer-platform/issues/51
- [x] Clean up: `DURABLE_TASKS` if/defs https://github.com/microsoft/developer-platform/pull/65
- [x] Clean up: don't set id/tenant explicitly https://github.com/microsoft/developer-platform/pull/50#discussion_r1462144817
- [ ] Clean up: https://github.com/microsoft/developer-platform/pull/50#discussion_r1462193880) https://github.com/microsoft/developer-platform/pull/73
- [x] Ensure both samples are up-to-date showing an operation being returned and handling operations for GET
```

_Originally posted by @twsouthwick in https://github.com/microsoft/developer-platform/issues/45#issuecomment-1901258511_
